# Paths to data files
data: 
    dwd: /Users/skyfano/Documents/Masterarbeit/Prediction_of_energy_prices/data/DWD/storage
    eex_input: /Users/skyfano/Documents/Masterarbeit/Prediction_of_energy_prices/data/EEX_stock/storage/prices_per_year
    eex_saving: /Users/skyfano/Documents/Masterarbeit/Prediction_of_energy_prices/data/EEX_stock/storage/final_data_eex
bboxes:
    germany:  [5.98865807458, 47.3024876979, 15.0169958839, 54.983104153]