optuna_trials: 500      # trials for hyperparameter tuning
optuna_epochs: 101       # Number epochs for fitting per trial
best_model_epochs: 101   # Final model training epochs
n_jobs: 6                # Number of parallel Optuna trials
devices: 1               # Number of GPUs to utilize
max_input_chunk_length: 250
