optuna_trials: 5      # trials for hyperparameter tuning
optuna_epochs: 5       # Number epochs for fitting per trial
best_model_epochs: 5   # Final model training epochs
n_jobs: 5                # Number of parallel Optuna trials
devices: 1               # Number of GPUs to utilize
lags: False              # Use lags in the model
max_input_chunk_length: 300
