optuna_trials: 500      # trials for hyperparameter tuning
optuna_epochs: 200       # Number epochs for fitting per trial
best_model_epochs: 200   # Final model training epochs
n_jobs: 6                # Number of parallel Optuna trials
devices: 1               # Number of GPUs to utilize
lags: False              # Use lags in the model
max_input_chunk_length: 300
